In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os, warnings, matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

warnings.filterwarnings('ignore')
plt.style.use('ggplot')

font_location = 'C:/Windows/Fonts/HYCYSM.TTF'
font_name = fm.FontProperties(fname = font_location).get_name()
matplotlib.rc('font', family=font_name)

In [2]:
url = 'UseData/SmartFarm/'
os.listdir(url)

['경기도_박--농가데이터셋_딸기.xlsx',
 '경기도_현--농가데이터셋_딸기.xlsx',
 '경상남도_양--농가데이터셋_딸기.xlsx',
 '경상북도_박--농가데이터셋_딸기.xlsx',
 '광주광역시_김--농가데이터셋_딸기.xlsx',
 '대전광역시_안--농가데이터셋_딸기.xlsx',
 '전라남도_류--농가데이터셋_딸기.xlsx',
 '전라남도_심--농가데이터셋_딸기.xlsx',
 '전라북도_강--농가데이터셋_딸기.xlsx',
 '전라북도_유--농가데이터셋_딸기.xlsx',
 '충청남도_김--농가데이터셋_딸기.xlsx']

In [4]:
df = pd.read_excel(url + os.listdir(url)[0], sheet_name='Sheet 1')

In [5]:
df.columns

Index(['시설ID', '농가명', '시도', '시군구', '품목명', '품종', '재배면적', '시설유형', '재배형태',
       '단동/연동 구분', '수집일', '외부온도', '외부습도', '외부 일사량', '외부풍향', '외부풍속', '외부강우',
       '강우감지', '내부온도', '내부습도', '내부CO2', '내부 일사량', '토양EC', '토양PH', '지온', '지습',
       '(양액)총배액', '(양액)총급액', '(양액)배액PH', '(양액)공급PH', '(양액)배액EC', '(양액)공급EC',
       '(양액)지온', '(양액)지습', '배기팬작동여부', 'CO2발생장치작동여부', '보광등작동여부', '난방기작동상태',
       '난방기작동여부', '유동팬작동상태', '유동팬작동여부', '보온커튼작동상태', '보온커튼작동여부', '차광커튼작동상태',
       '차광커튼작동여부', '우측삼중측창 작동여부', '좌측삼중측창 작동여부', '우측이중측창 작동여부', '좌측이중측창 작동여부',
       '우측일중측창 개도', '우측일중측창 온도폭', '우측일중측창 설정온도', '우측일중측창 작동여부', '우측일중측창 작동상태',
       '좌측일중측창 개도', '좌측일중측창 온도폭', '좌측일중측창 설정온도', '좌측일중측창 작동여부', '좌측일중측창 작동상태',
       '측창', '우측이중천창 작동여부', '좌측이중천창 작동여부', '우측일중천창 개도', '우측일중천창 온도폭',
       '우측일중천창 설정온도', '우측일중천창 작동여부', '우측일중천창 작동상태', '좌측일중천창 개도', '좌측일중천창 온도폭',
       '좌측일중천창 설정온도', '좌측일중천창 작동여부', '좌측일중천창 작동상태', '천창', '조사일', '주차', '초장',
       '엽장', '엽폭', '엽병장', '엽수', '관부직경', '화방 꽃수(소화수)', '착과수', '최종화방차수'],
      dtype='object')

In [10]:
target_col = ['조사일', '주차', '초장', '엽장', '엽폭', '엽병장', 
              '엽수', '관부직경', '화방 꽃수(소화수)', '착과수', '최종화방차수']
X_col = ['시설ID', '농가명', '시도', '시군구', '품목명', '품종', '재배면적', '시설유형', '재배형태',
       '단동/연동 구분', '수집일', '외부온도', '외부습도', '외부 일사량', '외부풍향', '외부풍속', '외부강우',
       '강우감지', '내부온도', '내부습도', '내부CO2', '내부 일사량', '토양EC', '토양PH', '지온', '지습',
       '(양액)총배액', '(양액)총급액', '(양액)배액PH', '(양액)공급PH', '(양액)배액EC', '(양액)공급EC',
       '(양액)지온', '(양액)지습', '배기팬작동여부', 'CO2발생장치작동여부', '보광등작동여부', '난방기작동상태',
       '난방기작동여부', '유동팬작동상태', '유동팬작동여부', '보온커튼작동상태', '보온커튼작동여부', '차광커튼작동상태',
       '차광커튼작동여부', '우측삼중측창 작동여부', '좌측삼중측창 작동여부', '우측이중측창 작동여부', '좌측이중측창 작동여부',
       '우측일중측창 개도', '우측일중측창 온도폭', '우측일중측창 설정온도', '우측일중측창 작동여부', '우측일중측창 작동상태',
       '좌측일중측창 개도', '좌측일중측창 온도폭', '좌측일중측창 설정온도', '좌측일중측창 작동여부', '좌측일중측창 작동상태',
       '측창', '우측이중천창 작동여부', '좌측이중천창 작동여부', '우측일중천창 개도', '우측일중천창 온도폭',
       '우측일중천창 설정온도', '우측일중천창 작동여부', '우측일중천창 작동상태', '좌측일중천창 개도', '좌측일중천창 온도폭',
       '좌측일중천창 설정온도', '좌측일중천창 작동여부', '좌측일중천창 작동상태', '천창']

len(df.columns), len(target_col), len(X_col)

(84, 11, 73)

In [8]:
df.head()

,시설ID,농가명,시도,시군구,품목명,품종,재배면적,시설유형,재배형태,단동/연동 구분,...,주차,초장,엽장,엽폭,엽병장,엽수,관부직경,화방 꽃수(소화수),착과수,최종화방차수
0,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df.describe()

,재배면적,외부온도,외부습도,외부 일사량,외부풍향,외부풍속,외부강우,강우감지,내부온도,내부습도,...,천창,초장,엽장,엽폭,엽병장,엽수,관부직경,화방 꽃수(소화수),착과수,최종화방차수
count,3322.0,3319.000000,0.0,3319.000000,0.0,3320.000000,0.0,3319.000000,3319.000000,3319.000000,...,0.0,444.000000,420.000000,443.000000,397.000000,349.000000,420.000000,234.000000,374.000000,212.000000
mean,1587.0,11.022040,NaN,182.111503,NaN,0.620675,NaN,0.060455,14.919774,85.492359,...,NaN,25.839775,9.004810,8.868962,15.058186,8.825989,19.699881,0.988632,7.497754,4.373066
std,0.0,8.980139,NaN,254.709438,NaN,0.881151,NaN,0.213827,5.838042,11.594340,...,NaN,2.217645,0.619202,6.423960,2.065872,2.032039,0.736942,0.728752,2.656339,1.363764
min,1587.0,-14.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,3.050000,52.180000,...,NaN,22.400000,8.000000,6.750000,12.230000,6.250000,18.470000,0.000000,2.670000,2.750000
25%,1587.0,4.420000,NaN,0.000000,NaN,0.000000,NaN,0.000000,9.360000,78.725000,...,NaN,23.130000,8.530000,7.050000,12.800000,7.000000,19.000000,0.330000,6.000000,3.250000
50%,1587.0,11.820000,NaN,20.960000,NaN,0.220000,NaN,0.000000,15.320000,89.450000,...,NaN,27.050000,8.830000,7.300000,15.650000,8.330000,19.850000,1.000000,8.000000,4.000000
75%,1587.0,17.680000,NaN,326.440000,NaN,0.910000,NaN,0.000000,19.630000,94.280000,...,NaN,27.680000,9.530000,7.770000,17.030000,11.000000,20.450000,1.500000,9.627500,5.330000
max,1587.0,31.910000,NaN,959.650000,NaN,5.060000,NaN,1.000000,29.070000,100.000000,...,NaN,28.670000,10.300000,36.230000,17.330000,12.670000,20.680000,2.250000,11.250000,7.000000

    1. 컬럼 별 결측값 갯수 확인해보고 --> 이게 제일 중요할듯 하도 비어있는게 많아서.
    2. 결측값 있는 행들 일단 지워서 sns heatmap을 그려보자.