In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import os, warnings, matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

warnings.filterwarnings('ignore')
plt.style.use('ggplot')

font_location = 'C:/Windows/Fonts/HYCYSM.TTF'
font_name = fm.FontProperties(fname = font_location).get_name()
matplotlib.rc('font', family=font_name)

In [25]:
url = 'UseData/SmartFarm/'
os.listdir(url)

['경기도_박--농가데이터셋_딸기.xlsx',
 '경기도_현--농가데이터셋_딸기.xlsx',
 '경상남도_양--농가데이터셋_딸기.xlsx',
 '경상북도_박--농가데이터셋_딸기.xlsx',
 '광주광역시_김--농가데이터셋_딸기.xlsx',
 '대전광역시_안--농가데이터셋_딸기.xlsx',
 '전라남도_류--농가데이터셋_딸기.xlsx',
 '전라남도_심--농가데이터셋_딸기.xlsx',
 '전라북도_강--농가데이터셋_딸기.xlsx',
 '전라북도_유--농가데이터셋_딸기.xlsx',
 '충청남도_김--농가데이터셋_딸기.xlsx']

In [9]:
df = pd.read_excel(url + os.listdir(url)[0], sheet_name='Sheet 1')

In [10]:
df.columns

Index(['시설ID', '농가명', '시도', '시군구', '품목명', '품종', '재배면적', '시설유형', '재배형태',
       '단동/연동 구분', '수집일', '외부온도', '외부습도', '외부 일사량', '외부풍향', '외부풍속', '외부강우',
       '강우감지', '내부온도', '내부습도', '내부CO2', '내부 일사량', '토양EC', '토양PH', '지온', '지습',
       '(양액)총배액', '(양액)총급액', '(양액)배액PH', '(양액)공급PH', '(양액)배액EC', '(양액)공급EC',
       '(양액)지온', '(양액)지습', '배기팬작동여부', 'CO2발생장치작동여부', '보광등작동여부', '난방기작동상태',
       '난방기작동여부', '유동팬작동상태', '유동팬작동여부', '보온커튼작동상태', '보온커튼작동여부', '차광커튼작동상태',
       '차광커튼작동여부', '우측삼중측창 작동여부', '좌측삼중측창 작동여부', '우측이중측창 작동여부', '좌측이중측창 작동여부',
       '우측일중측창 개도', '우측일중측창 온도폭', '우측일중측창 설정온도', '우측일중측창 작동여부', '우측일중측창 작동상태',
       '좌측일중측창 개도', '좌측일중측창 온도폭', '좌측일중측창 설정온도', '좌측일중측창 작동여부', '좌측일중측창 작동상태',
       '측창', '우측이중천창 작동여부', '좌측이중천창 작동여부', '우측일중천창 개도', '우측일중천창 온도폭',
       '우측일중천창 설정온도', '우측일중천창 작동여부', '우측일중천창 작동상태', '좌측일중천창 개도', '좌측일중천창 온도폭',
       '좌측일중천창 설정온도', '좌측일중천창 작동여부', '좌측일중천창 작동상태', '천창', '조사일', '주차', '초장',
       '엽장', '엽폭', '엽병장', '엽수', '관부직경', '화방 꽃수(소화수)', '착과수', '최종화방차수'],
      dtype='object')

In [11]:
target_col = ['조사일', '주차', '초장', '엽장', '엽폭', '엽병장', 
              '엽수', '관부직경', '화방 꽃수(소화수)', '착과수', '최종화방차수']
X_col = ['시설ID', '농가명', '시도', '시군구', '품목명', '품종', '재배면적', '시설유형', '재배형태',
       '단동/연동 구분', '수집일', '외부온도', '외부습도', '외부 일사량', '외부풍향', '외부풍속', '외부강우',
       '강우감지', '내부온도', '내부습도', '내부CO2', '내부 일사량', '토양EC', '토양PH', '지온', '지습',
       '(양액)총배액', '(양액)총급액', '(양액)배액PH', '(양액)공급PH', '(양액)배액EC', '(양액)공급EC',
       '(양액)지온', '(양액)지습', '배기팬작동여부', 'CO2발생장치작동여부', '보광등작동여부', '난방기작동상태',
       '난방기작동여부', '유동팬작동상태', '유동팬작동여부', '보온커튼작동상태', '보온커튼작동여부', '차광커튼작동상태',
       '차광커튼작동여부', '우측삼중측창 작동여부', '좌측삼중측창 작동여부', '우측이중측창 작동여부', '좌측이중측창 작동여부',
       '우측일중측창 개도', '우측일중측창 온도폭', '우측일중측창 설정온도', '우측일중측창 작동여부', '우측일중측창 작동상태',
       '좌측일중측창 개도', '좌측일중측창 온도폭', '좌측일중측창 설정온도', '좌측일중측창 작동여부', '좌측일중측창 작동상태',
       '측창', '우측이중천창 작동여부', '좌측이중천창 작동여부', '우측일중천창 개도', '우측일중천창 온도폭',
       '우측일중천창 설정온도', '우측일중천창 작동여부', '우측일중천창 작동상태', '좌측일중천창 개도', '좌측일중천창 온도폭',
       '좌측일중천창 설정온도', '좌측일중천창 작동여부', '좌측일중천창 작동상태', '천창']

len(df.columns), len(target_col), len(X_col)

(84, 11, 73)

In [12]:
df.head()

,시설ID,농가명,시도,시군구,품목명,품종,재배면적,시설유형,재배형태,단동/연동 구분,...,주차,초장,엽장,엽폭,엽병장,엽수,관부직경,화방 꽃수(소화수),착과수,최종화방차수
0,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,PF_0020717_01,박*,경기도,광주시,딸기,설향,1587,비닐,수경,연동,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.describe()

,재배면적,외부온도,외부습도,외부 일사량,외부풍향,외부풍속,외부강우,강우감지,내부온도,내부습도,...,천창,초장,엽장,엽폭,엽병장,엽수,관부직경,화방 꽃수(소화수),착과수,최종화방차수
count,3322.0,3319.000000,0.0,3319.000000,0.0,3320.000000,0.0,3319.000000,3319.000000,3319.000000,...,0.0,444.000000,420.000000,443.000000,397.000000,349.000000,420.000000,234.000000,374.000000,212.000000
mean,1587.0,11.022040,NaN,182.111503,NaN,0.620675,NaN,0.060455,14.919774,85.492359,...,NaN,25.839775,9.004810,8.868962,15.058186,8.825989,19.699881,0.988632,7.497754,4.373066
std,0.0,8.980139,NaN,254.709438,NaN,0.881151,NaN,0.213827,5.838042,11.594340,...,NaN,2.217645,0.619202,6.423960,2.065872,2.032039,0.736942,0.728752,2.656339,1.363764
min,1587.0,-14.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,3.050000,52.180000,...,NaN,22.400000,8.000000,6.750000,12.230000,6.250000,18.470000,0.000000,2.670000,2.750000
25%,1587.0,4.420000,NaN,0.000000,NaN,0.000000,NaN,0.000000,9.360000,78.725000,...,NaN,23.130000,8.530000,7.050000,12.800000,7.000000,19.000000,0.330000,6.000000,3.250000
50%,1587.0,11.820000,NaN,20.960000,NaN,0.220000,NaN,0.000000,15.320000,89.450000,...,NaN,27.050000,8.830000,7.300000,15.650000,8.330000,19.850000,1.000000,8.000000,4.000000
75%,1587.0,17.680000,NaN,326.440000,NaN,0.910000,NaN,0.000000,19.630000,94.280000,...,NaN,27.680000,9.530000,7.770000,17.030000,11.000000,20.450000,1.500000,9.627500,5.330000
max,1587.0,31.910000,NaN,959.650000,NaN,5.060000,NaN,1.000000,29.070000,100.000000,...,NaN,28.670000,10.300000,36.230000,17.330000,12.670000,20.680000,2.250000,11.250000,7.000000

    1. 컬럼 별 결측값 갯수 확인해보고 --> 이게 제일 중요할듯 하도 비어있는게 많아서.
    2. 결측값 있는 행들 일단 지워서 sns heatmap을 그려보자.

In [9]:
df[target_col].describe()

,초장,엽장,엽폭,엽병장,엽수,관부직경,화방 꽃수(소화수),착과수,최종화방차수
count,444.000000,420.000000,443.000000,397.000000,349.000000,420.000000,234.000000,374.000000,212.000000
mean,25.839775,9.004810,8.868962,15.058186,8.825989,19.699881,0.988632,7.497754,4.373066
std,2.217645,0.619202,6.423960,2.065872,2.032039,0.736942,0.728752,2.656339,1.363764
min,22.400000,8.000000,6.750000,12.230000,6.250000,18.470000,0.000000,2.670000,2.750000
25%,23.130000,8.530000,7.050000,12.800000,7.000000,19.000000,0.330000,6.000000,3.250000
50%,27.050000,8.830000,7.300000,15.650000,8.330000,19.850000,1.000000,8.000000,4.000000
75%,27.680000,9.530000,7.770000,17.030000,11.000000,20.450000,1.500000,9.627500,5.330000
max,28.670000,10.300000,36.230000,17.330000,12.670000,20.680000,2.250000,11.250000,7.000000

In [13]:
df[X_col].describe()

,재배면적,외부온도,외부습도,외부 일사량,외부풍향,외부풍속,외부강우,강우감지,내부온도,내부습도,...,우측일중천창 온도폭,우측일중천창 설정온도,우측일중천창 작동여부,우측일중천창 작동상태,좌측일중천창 개도,좌측일중천창 온도폭,좌측일중천창 설정온도,좌측일중천창 작동여부,좌측일중천창 작동상태,천창
count,3322.0,3319.000000,0.0,3319.000000,0.0,3320.000000,0.0,3319.000000,3319.000000,3319.000000,...,0.0,0.0,3319.000000,0.0,0.0,0.0,0.0,3319.000000,0.0,0.0
mean,1587.0,11.022040,NaN,182.111503,NaN,0.620675,NaN,0.060455,14.919774,85.492359,...,NaN,NaN,41.348762,NaN,NaN,NaN,NaN,40.280642,NaN,NaN
std,0.0,8.980139,NaN,254.709438,NaN,0.881151,NaN,0.213827,5.838042,11.594340,...,NaN,NaN,44.194169,NaN,NaN,NaN,NaN,44.482273,NaN,NaN
min,1587.0,-14.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,3.050000,52.180000,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,1587.0,4.420000,NaN,0.000000,NaN,0.000000,NaN,0.000000,9.360000,78.725000,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
50%,1587.0,11.820000,NaN,20.960000,NaN,0.220000,NaN,0.000000,15.320000,89.450000,...,NaN,NaN,16.820000,NaN,NaN,NaN,NaN,12.270000,NaN,NaN
75%,1587.0,17.680000,NaN,326.440000,NaN,0.910000,NaN,0.000000,19.630000,94.280000,...,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,100.000000,NaN,NaN
max,1587.0,31.910000,NaN,959.650000,NaN,5.060000,NaN,1.000000,29.070000,100.000000,...,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,100.000000,NaN,NaN

    현재 Look-up으로 봤을 때 불필요해보이는 컬럼?
        1. 시설ID : 단순 구분자.
        2. 농가명/시도/시군구/품목명/품종 : 파일 이름으로 구분 가능
        3. 시설유형/재배형태/단동연동 구분 : 이거도 어떻게 보면 구분자?
           -> 무엇보다 target에 직접적인 영향을 미칠 수치데이터가 아님.
    얘네를 먼저 drop 해보자.

In [13]:
X_col = ['수집일', '외부온도', '외부습도', '외부 일사량', '외부풍향', '외부풍속', '외부강우',
       '강우감지', '내부온도', '내부습도', '내부CO2', '내부 일사량', '토양EC', '토양PH', '지온', '지습',
       '(양액)총배액', '(양액)총급액', '(양액)배액PH', '(양액)공급PH', '(양액)배액EC', '(양액)공급EC',
       '(양액)지온', '(양액)지습', '배기팬작동여부', 'CO2발생장치작동여부', '보광등작동여부', '난방기작동상태',
       '난방기작동여부', '유동팬작동상태', '유동팬작동여부', '보온커튼작동상태', '보온커튼작동여부', '차광커튼작동상태',
       '차광커튼작동여부', '우측삼중측창 작동여부', '좌측삼중측창 작동여부', '우측이중측창 작동여부', '좌측이중측창 작동여부',
       '우측일중측창 개도', '우측일중측창 온도폭', '우측일중측창 설정온도', '우측일중측창 작동여부', '우측일중측창 작동상태',
       '좌측일중측창 개도', '좌측일중측창 온도폭', '좌측일중측창 설정온도', '좌측일중측창 작동여부', '좌측일중측창 작동상태',
       '측창', '우측이중천창 작동여부', '좌측이중천창 작동여부', '우측일중천창 개도', '우측일중천창 온도폭',
       '우측일중천창 설정온도', '우측일중천창 작동여부', '우측일중천창 작동상태', '좌측일중천창 개도', '좌측일중천창 온도폭',
       '좌측일중천창 설정온도', '좌측일중천창 작동여부', '좌측일중천창 작동상태', '천창']
df[X_col].describe()

,외부온도,외부습도,외부 일사량,외부풍향,외부풍속,외부강우,강우감지,내부온도,내부습도,내부CO2,...,우측일중천창 온도폭,우측일중천창 설정온도,우측일중천창 작동여부,우측일중천창 작동상태,좌측일중천창 개도,좌측일중천창 온도폭,좌측일중천창 설정온도,좌측일중천창 작동여부,좌측일중천창 작동상태,천창
count,3319.000000,0.0,3319.000000,0.0,3320.000000,0.0,3319.000000,3319.000000,3319.000000,3319.000000,...,0.0,0.0,3319.000000,0.0,0.0,0.0,0.0,3319.000000,0.0,0.0
mean,11.022040,NaN,182.111503,NaN,0.620675,NaN,0.060455,14.919774,85.492359,506.298186,...,NaN,NaN,41.348762,NaN,NaN,NaN,NaN,40.280642,NaN,NaN
std,8.980139,NaN,254.709438,NaN,0.881151,NaN,0.213827,5.838042,11.594340,247.461162,...,NaN,NaN,44.194169,NaN,NaN,NaN,NaN,44.482273,NaN,NaN
min,-14.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,3.050000,52.180000,310.570000,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,4.420000,NaN,0.000000,NaN,0.000000,NaN,0.000000,9.360000,78.725000,402.860000,...,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
50%,11.820000,NaN,20.960000,NaN,0.220000,NaN,0.000000,15.320000,89.450000,447.320000,...,NaN,NaN,16.820000,NaN,NaN,NaN,NaN,12.270000,NaN,NaN
75%,17.680000,NaN,326.440000,NaN,0.910000,NaN,0.000000,19.630000,94.280000,504.625000,...,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,100.000000,NaN,NaN
max,31.910000,NaN,959.650000,NaN,5.060000,NaN,1.000000,29.070000,100.000000,2782.000000,...,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,100.000000,NaN,NaN

In [14]:
# 결측값 수나 한번 세보자.
df[X_col].isnull().sum()

수집일               0
외부온도              3
외부습도           3322
외부 일사량            3
외부풍향           3322
               ...
좌측일중천창 온도폭     3322
좌측일중천창 설정온도    3322
좌측일중천창 작동여부       3
좌측일중천창 작동상태    3322
천창             3322
Length: 63, dtype: int64

In [16]:
len(df['외부온도']), df['외부온도'].isnull().sum()

(3322, 3)

In [15]:
# 반복문 loop 돌려서 컬럼이 총 몇개인데
# 결측값이 얼마나 있는지 count하는 함수를 만들어서 세면 편하지 않을까?
print(f'<{os.listdir(url)[0]} 데이터 셋 속성 정보>')
print('\n')
for variable in X_col:
    print(f'"{variable}" 속성 전체 데이터 수 : ', len(df[variable]))
    print(f'"{variable}" 속성 결측값 수 : ', df[variable].isnull().sum())
    print('==========================================================')

print('\n')
print('95% 이상이 결측치인 속성은')
print('\n')

notAvailable = []
for variable in X_col:
    if df[variable].isnull().sum() >= (0.95 * len(df[variable])):
        # print(variable)
        notAvailable.append(variable)

for word in notAvailable:
    print(word)

print('\n')
print(f'와 같으며, 이런 속성의 갯수는 총 {len(notAvailable)} 개.')

print('\n')
print(f'전체 속성 {len(X_col)}개 중 사용할 수 없을 것이라 판단되는 속성 {len(notAvailable)}개를 제외하면 \n')
print(f'순수히 분석에 총 사용할 수 있을 속성은 {len(X_col)-len(notAvailable)} 개 이며,')
print('이런 조건을 만족하는 속성을 다음과 같이 추릴 수 있다 : ')
print('\n')

available = list(set(X_col).difference(set(notAvailable)))
for word in available:
    print(word)

<경기도_박--농가데이터셋_딸기.xlsx 데이터 셋 속성 정보>


"수집일" 속성 전체 데이터 수 :  3322
"수집일" 속성 결측값 수 :  0
==========================================================
"외부온도" 속성 전체 데이터 수 :  3322
"외부온도" 속성 결측값 수 :  3
==========================================================
"외부습도" 속성 전체 데이터 수 :  3322
"외부습도" 속성 결측값 수 :  3322
==========================================================
"외부 일사량" 속성 전체 데이터 수 :  3322
"외부 일사량" 속성 결측값 수 :  3
==========================================================
"외부풍향" 속성 전체 데이터 수 :  3322
"외부풍향" 속성 결측값 수 :  3322
==========================================================
"외부풍속" 속성 전체 데이터 수 :  3322
"외부풍속" 속성 결측값 수 :  2
==========================================================
"외부강우" 속성 전체 데이터 수 :  3322
"외부강우" 속성 결측값 수 :  3322
==========================================================
"강우감지" 속성 전체 데이터 수 :  3322
"강우감지" 속성 결측값 수 :  3
==========================================================
"내부온도" 속성 전체 데이터 수 :  3322
"내부온도" 속성 결측값 수 :  3
==========================================================
"내부습도" 속성 전체 데이터 수 :  3322
"내부습도" 속성 결측값 수 :  3
==========================================================
"내부CO2" 속성 전체 데이터 수 :  3322
"내부CO2" 속성 결측값 수 :  3
==========================================================
"내부 일사량" 속성 전체 데이터 수 :  3322
"내부 일사량" 속성 결측값 수 :  3322
==========================================================
"토양EC" 속성 전체 데이터 수 :  3322
"토양EC" 속성 결측값 수 :  3322
==========================================================
"토양PH" 속성 전체 데이터 수 :  3322
"토양PH" 속성 결측값 수 :  3322
==========================================================
"지온" 속성 전체 데이터 수 :  3322
"지온" 속성 결측값 수 :  427
==========================================================
"지습" 속성 전체 데이터 수 :  3322
"지습" 속성 결측값 수 :  3322
==========================================================
"(양액)총배액" 속성 전체 데이터 수 :  3322
"(양액)총배액" 속성 결측값 수 :  3322
==========================================================
"(양액)총급액" 속성 전체 데이터 수 :  3322
"(양액)총급액" 속성 결측값 수 :  3322
==========================================================
"(양액)배액PH" 속성 전체 데이터 수 :  3322
"(양액)배액PH" 속성 결측값 수 :  3322
==========================================================
"(양액)공급PH" 속성 전체 데이터 수 :  3322
"(양액)공급PH" 속성 결측값 수 :  3322
==========================================================
"(양액)배액EC" 속성 전체 데이터 수 :  3322
"(양액)배액EC" 속성 결측값 수 :  3322
==========================================================
"(양액)공급EC" 속성 전체 데이터 수 :  3322
"(양액)공급EC" 속성 결측값 수 :  3322
==========================================================
"(양액)지온" 속성 전체 데이터 수 :  3322
"(양액)지온" 속성 결측값 수 :  3322
==========================================================
"(양액)지습" 속성 전체 데이터 수 :  3322
"(양액)지습" 속성 결측값 수 :  428
==========================================================
"배기팬작동여부" 속성 전체 데이터 수 :  3322
"배기팬작동여부" 속성 결측값 수 :  3322
==========================================================
"CO2발생장치작동여부" 속성 전체 데이터 수 :  3322
"CO2발생장치작동여부" 속성 결측값 수 :  3322
==========================================================
"보광등작동여부" 속성 전체 데이터 수 :  3322
"보광등작동여부" 속성 결측값 수 :  3322
==========================================================
"난방기작동상태" 속성 전체 데이터 수 :  3322
"난방기작동상태" 속성 결측값 수 :  3322
==========================================================
"난방기작동여부" 속성 전체 데이터 수 :  3322
"난방기작동여부" 속성 결측값 수 :  3322
==========================================================
"유동팬작동상태" 속성 전체 데이터 수 :  3322
"유동팬작동상태" 속성 결측값 수 :  3322
==========================================================
"유동팬작동여부" 속성 전체 데이터 수 :  3322
"유동팬작동여부" 속성 결측값 수 :  3322
==========================================================
"보온커튼작동상태" 속성 전체 데이터 수 :  3322
"보온커튼작동상태" 속성 결측값 수 :  3322
==========================================================
"보온커튼작동여부" 속성 전체 데이터 수 :  3322
"보온커튼작동여부" 속성 결측값 수 :  3322
==========================================================
"차광커튼작동상태" 속성 전체 데이터 수 :  3322
"차광커튼작동상태" 속성 결측값 수 :  3
==========================================================
"차광커튼작동여부" 속성 전체 데이터 수 :  3322
"차광커튼작동여부" 속성 결측값 수 :  3322
==========================================================
"우측삼중측창 작동여부" 속성 전체 데이터 수 :  3322
"우측삼중측창 작동여부" 속성 결측값 수 :  3322
==========================================================
"좌측삼중측창 작동여부" 속성 전체 데이터 수 :  3322
"좌측삼중측창 작동여부" 속성 결측값 수 :  3322
==========================================================
"우측이중측창 작동여부" 속성 전체 데이터 수 :  3322
"우측이중측창 작동여부" 속성 결측값 수 :  3322
==========================================================
"좌측이중측창 작동여부" 속성 전체 데이터 수 :  3322
"좌측이중측창 작동여부" 속성 결측값 수 :  3322
==========================================================
"우측일중측창 개도" 속성 전체 데이터 수 :  3322
"우측일중측창 개도" 속성 결측값 수 :  3322
==========================================================
"우측일중측창 온도폭" 속성 전체 데이터 수 :  3322
"우측일중측창 온도폭" 속성 결측값 수 :  3322
==========================================================
"우측일중측창 설정온도" 속성 전체 데이터 수 :  3322
"우측일중측창 설정온도" 속성 결측값 수 :  3322
==========================================================
"우측일중측창 작동여부" 속성 전체 데이터 수 :  3322
"우측일중측창 작동여부" 속성 결측값 수 :  3322
==========================================================
"우측일중측창 작동상태" 속성 전체 데이터 수 :  3322
"우측일중측창 작동상태" 속성 결측값 수 :  3322
==========================================================
"좌측일중측창 개도" 속성 전체 데이터 수 :  3322
"좌측일중측창 개도" 속성 결측값 수 :  3322
==========================================================
"좌측일중측창 온도폭" 속성 전체 데이터 수 :  3322
"좌측일중측창 온도폭" 속성 결측값 수 :  3322
==========================================================
"좌측일중측창 설정온도" 속성 전체 데이터 수 :  3322
"좌측일중측창 설정온도" 속성 결측값 수 :  3322
==========================================================
"좌측일중측창 작동여부" 속성 전체 데이터 수 :  3322
"좌측일중측창 작동여부" 속성 결측값 수 :  3
==========================================================
"좌측일중측창 작동상태" 속성 전체 데이터 수 :  3322
"좌측일중측창 작동상태" 속성 결측값 수 :  3322
==========================================================
"측창" 속성 전체 데이터 수 :  3322
"측창" 속성 결측값 수 :  3322
==========================================================
"우측이중천창 작동여부" 속성 전체 데이터 수 :  3322
"우측이중천창 작동여부" 속성 결측값 수 :  2
==========================================================
"좌측이중천창 작동여부" 속성 전체 데이터 수 :  3322
"좌측이중천창 작동여부" 속성 결측값 수 :  3
==========================================================
"우측일중천창 개도" 속성 전체 데이터 수 :  3322
"우측일중천창 개도" 속성 결측값 수 :  3322
==========================================================
"우측일중천창 온도폭" 속성 전체 데이터 수 :  3322
"우측일중천창 온도폭" 속성 결측값 수 :  3322
==========================================================
"우측일중천창 설정온도" 속성 전체 데이터 수 :  3322
"우측일중천창 설정온도" 속성 결측값 수 :  3322
==========================================================
"우측일중천창 작동여부" 속성 전체 데이터 수 :  3322
"우측일중천창 작동여부" 속성 결측값 수 :  3
==========================================================
"우측일중천창 작동상태" 속성 전체 데이터 수 :  3322
"우측일중천창 작동상태" 속성 결측값 수 :  3322
==========================================================
"좌측일중천창 개도" 속성 전체 데이터 수 :  3322
"좌측일중천창 개도" 속성 결측값 수 :  3322
==========================================================
"좌측일중천창 온도폭" 속성 전체 데이터 수 :  3322
"좌측일중천창 온도폭" 속성 결측값 수 :  3322
==========================================================
"좌측일중천창 설정온도" 속성 전체 데이터 수 :  3322
"좌측일중천창 설정온도" 속성 결측값 수 :  3322
==========================================================
"좌측일중천창 작동여부" 속성 전체 데이터 수 :  3322
"좌측일중천창 작동여부" 속성 결측값 수 :  3
==========================================================
"좌측일중천창 작동상태" 속성 전체 데이터 수 :  3322
"좌측일중천창 작동상태" 속성 결측값 수 :  3322
==========================================================
"천창" 속성 전체 데이터 수 :  3322
"천창" 속성 결측값 수 :  3322
==========================================================


95% 이상이 결측치인 속성은


외부습도
외부풍향
외부강우
내부 일사량
토양EC
토양PH
지습
(양액)총배액
(양액)총급액
(양액)배액PH
(양액)공급PH
(양액)배액EC
(양액)공급EC
(양액)지온
배기팬작동여부
CO2발생장치작동여부
보광등작동여부
난방기작동상태
난방기작동여부
유동팬작동상태
유동팬작동여부
보온커튼작동상태
보온커튼작동여부
차광커튼작동여부
우측삼중측창 작동여부
좌측삼중측창 작동여부
우측이중측창 작동여부
좌측이중측창 작동여부
우측일중측창 개도
우측일중측창 온도폭
우측일중측창 설정온도
우측일중측창 작동여부
우측일중측창 작동상태
좌측일중측창 개도
좌측일중측창 온도폭
좌측일중측창 설정온도
좌측일중측창 작동상태
측창
우측일중천창 개도
우측일중천창 온도폭
우측일중천창 설정온도
우측일중천창 작동상태
좌측일중천창 개도
좌측일중천창 온도폭
좌측일중천창 설정온도
좌측일중천창 작동상태
천창


와 같으며, 이런 속성의 갯수는 총 47 개.


전체 속성 63개 중 사용할 수 없을 것이라 판단되는 속성 47개를 제외하면

순수히 분석에 총 사용할 수 있을 속성은 16 개 이며,
이런 조건을 만족하는 속성을 다음과 같이 추릴 수 있다 :


수집일
(양액)지습
좌측일중측창 작동여부
외부풍속
지온
외부온도
좌측일중천창 작동여부
좌측이중천창 작동여부
외부 일사량
우측일중천창 작동여부
우측이중천창 작동여부
강우감지
내부습도
내부온도
차광커튼작동상태
내부CO2

    이걸 함수로 만들어서
    각 파일마다 txt 파일로 write?

In [34]:
available, len(available), target_col, len(target_col)

(['좌측이중천창 작동여부',
  '외부온도',
  '내부CO2',
  '(양액)지습',
  '내부온도',
  '차광커튼작동상태',
  '우측일중천창 작동여부',
  '내부습도',
  '지온',
  '좌측일중측창 작동여부',
  '우측이중천창 작동여부',
  '외부 일사량',
  '수집일',
  '강우감지',
  '외부풍속',
  '좌측일중천창 작동여부'],
 16,
 ['조사일',
  '주차',
  '초장',
  '엽장',
  '엽폭',
  '엽병장',
  '엽수',
  '관부직경',
  '화방 꽃수(소화수)',
  '착과수',
  '최종화방차수'],
 11)

In [35]:
os.listdir(url)

['경기도_박--농가데이터셋_딸기.xlsx',
 '경기도_현--농가데이터셋_딸기.xlsx',
 '경상남도_양--농가데이터셋_딸기.xlsx',
 '경상북도_박--농가데이터셋_딸기.xlsx',
 '광주광역시_김--농가데이터셋_딸기.xlsx',
 '대전광역시_안--농가데이터셋_딸기.xlsx',
 '전라남도_류--농가데이터셋_딸기.xlsx',
 '전라남도_심--농가데이터셋_딸기.xlsx',
 '전라북도_강--농가데이터셋_딸기.xlsx',
 '전라북도_유--농가데이터셋_딸기.xlsx',
 '충청남도_김--농가데이터셋_딸기.xlsx']

In [45]:
filesDF = pd.DataFrame({'File' : os.listdir(url)})
filesDF

                         File
0       경기도_문--농가데이터셋_딸기.xlsx
1       경기도_박--농가데이터셋_딸기.xlsx
2       경기도_안--농가데이터셋_딸기.xlsx
3       경기도_이--농가데이터셋_딸기.xlsx
4       경기도_장--농가데이터셋_딸기.xlsx
..                        ...
67     충청남도_정--농가데이터셋_딸기.xlsx
68     충청북도_신--농가데이터셋_딸기.xlsx
69  충청북도_이--(2)농가데이터셋_딸기.xlsx
70  충청북도_이--(3)농가데이터셋_딸기.xlsx
71     충청북도_이--농가데이터셋_딸기.xlsx

[72 rows x 1 columns]

In [50]:
txtURL = 'UseData/SmartFarmTXT/'
os.listdir(txtURL)

[]

In [58]:
target_col = ['조사일', '주차', '초장', '엽장', '엽폭', '엽병장', 
              '엽수', '관부직경', '화방 꽃수(소화수)', '착과수', '최종화방차수']
X_col = ['수집일', '외부온도', '외부습도', '외부 일사량', '외부풍향', '외부풍속', '외부강우',
       '강우감지', '내부온도', '내부습도', '내부CO2', '내부 일사량', '토양EC', '토양PH', '지온', '지습',
       '(양액)총배액', '(양액)총급액', '(양액)배액PH', '(양액)공급PH', '(양액)배액EC', '(양액)공급EC',
       '(양액)지온', '(양액)지습', '배기팬작동여부', 'CO2발생장치작동여부', '보광등작동여부', '난방기작동상태',
       '난방기작동여부', '유동팬작동상태', '유동팬작동여부', '보온커튼작동상태', '보온커튼작동여부', '차광커튼작동상태',
       '차광커튼작동여부', '우측삼중측창 작동여부', '좌측삼중측창 작동여부', '우측이중측창 작동여부', '좌측이중측창 작동여부',
       '우측일중측창 개도', '우측일중측창 온도폭', '우측일중측창 설정온도', '우측일중측창 작동여부', '우측일중측창 작동상태',
       '좌측일중측창 개도', '좌측일중측창 온도폭', '좌측일중측창 설정온도', '좌측일중측창 작동여부', '좌측일중측창 작동상태',
       '측창', '우측이중천창 작동여부', '좌측이중천창 작동여부', '우측일중천창 개도', '우측일중천창 온도폭',
       '우측일중천창 설정온도', '우측일중천창 작동여부', '우측일중천창 작동상태', '좌측일중천창 개도', '좌측일중천창 온도폭',
       '좌측일중천창 설정온도', '좌측일중천창 작동여부', '좌측일중천창 작동상태', '천창']

def TextWriter(url, file):
    # for textfiles in os.listdir(txtURL):
    # 해당 엑셀파일마다 loop돌면서 텍스트 파일에 write.
    # for textfiles in os.listdir(url): # 이게 문제였네 ㅅㅂ
    # 엑셀 파일 먼저 열고
    df = pd.read_excel(url + file, sheet_name='Sheet 1')
    # 텍스트 파일 열어서 (없다면 새로 생성) 아래 내용 작성.
    with open(txtURL + file[:-5] + '.txt', 'w+', encoding='utf8') as f:
        f.write(f'<{file} 데이터 셋 속성 정보>\n')
        f.write('\n')
        for variable in X_col:
            f.write(f'"{variable}" 속성 전체 데이터 수 : {len(df[variable])} \n')
            f.write(f'"{variable}" 속성 결측값 수 : {df[variable].isnull().sum()} \n')
            f.write('========================================================== \n')
        f.write('\n')
        f.write('## 95% 이상이 결측치인 속성은 ## \n')
        f.write('\n')
    
        notAvailable = []
        for variable in X_col:
            if df[variable].isnull().sum() >= (0.95 * len(df[variable])):
                notAvailable.append(variable)
        for word in notAvailable:
            f.write(f'{word} \n')
        f.write('\n')
        f.write(f'과(와) 같으며, 이런 속성의 갯수는 총 {len(notAvailable)} 개. \n')
            
        f.write('\n')
        f.write(f'전체 독립 속성 {len(X_col)}개 중 사용할 수 없을 것이라 판단되는 속성 {len(notAvailable)}개를 제외하면 \n')
        f.write(f'순수히 분석에 총 사용할 수 있을 속성은 {len(X_col)-len(notAvailable)} 개 이며, \n')
        f.write('이런 조건을 만족하는 속성을 다음과 같이 추릴 수 있다 : \n')
        f.write('\n')
            
        available = list(set(X_col).difference(set(notAvailable)))
        for word in available:
            f.write(f'{word} \n')

In [61]:
# for index in range(len(filesDF)):
    # print(url+filesDF['File'][index])
#for textfiles in os.listdir(txtURL):
#    print(txtURL + textfiles)

In [59]:
for index in range(len(filesDF)):
    TextWriter(url, filesDF['File'][index])

    아니 왜 전부다 똑같이 나오지??
    데이터셋 뭐 돌려먹기라도 했나??
    
    df가 for문 밖에서 선언되어서 그거 하나로 다 돌려먹기 하는구나 
    아닌데 다 다른데 ㅅㅂ 
    아니잖아 ㅅㅂ

In [31]:
for textfiles in os.listdir(txtURL):
    with open(textfiles, 'w', encoding='utf8') as f:
        f.write('외않되')

In [60]:
# os.listdir(url)
# for textfiles in os.listdir(url):
    # with open(txtURL + textfiles, 'w', encoding='utf8') as f:
        #f.write('되나?')
    # print(txtURL + textfiles[:-5] + '.txt')

    텍스트파일 생성 끝.